### ISSUE TITLE
Progress bar for workflow execution

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/ember-pipeline-monitor-frontend#1]
Progress bar, which will should how many steps are done and how many are yet to be done.
*****-------- (5 out of 13)
Or in percentage (does it make sense?)

**Comment by madnificent** [comment]
I doubt this has much value. You clearly see the pipeline by scrolling through it.  The pipeline steps also have an extrmely variable time to run.

If we could show the progress within a step, that could prove to be useful.  This would require for the component to share such content.

**Comment by earthquakesan** [comment]
I would agree on this one. I don't think, that it would be feasible to get information about progress from all the components. What do you think? I will close this one.
Regarding status reporting from the components, discussion is required (tech. call?)
